[package]
name = "rustdemo"
version = "0.1.0"
authors = ["alvaradojl <alvaradojl@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"

[[bin]]
name = "rustdemo"
path = "main.rs"
